package probe

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func factStr(f *Fact) string {
	if f == nil || f.Value == nil {
		if f != nil && f.Note == "conflict" {
			return "**CONFLICT** (" + strings.Join(f.Source, ", ") + ")"
		}
		return "unknown"
	}
	return fmt.Sprintf("%s  _(%s; %s)_", fmtFactVal(f.Value), f.Confidence, strings.Join(f.Source, ", "))
}

func fmtFactVal(v any) string {
	switch x := v.(type) {
	case uint64:
		if x >= 1<<20 && x%(1<<20) == 0 {
			return fmt.Sprintf("0x%x (%d MiB)", x, x>>20)
		}
		if x >= 1024 && x%1024 == 0 {
			return fmt.Sprintf("0x%x (%d KiB)", x, x>>10)
		}
		return fmt.Sprintf("%d", x)
	case float64:
		return fmt.Sprintf("%v", x)
	}
	return fmt.Sprint(v)
}

func hx(p *uint64) string {
	if p == nil {
		return "?"
	}
	return fmt.Sprintf("0x%08x", *p)
}

// WriteReports writes ursusboot-porting-report.md and ursusflasher-device-draft.json.
func WriteReports(dir string, p *Profile) error {
	if err := os.WriteFile(filepath.Join(dir, "ursusboot-porting-report.md"), []byte(ursusBootReport(p)), 0o644); err != nil {
		return err
	}
	b, err := json.MarshalIndent(ursusFlasherDraft(p), "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "ursusflasher-device-draft.json"), b, 0o644)
}

func ursusBootReport(p *Profile) string {
	var b strings.Builder
	w := func(f string, a ...any) { fmt.Fprintf(&b, f, a...) }
	w("# UrsusBoot porting report (preliminary)\n\n")
	w("Generated by %s %s from `profile.json` (%s, %s). Every value names its source and confidence; ", p.Generator["tool"], p.Generator["version"], p.Schema, p.Created)
	w("`unknown` means no source reported it, **CONFLICT** means sources disagree and nothing was chosen.\n\n")
	if miss, ok := p.Completeness["missing"].([]string); ok && len(miss) > 0 {
		w("> Incomplete profile — missing: %s\n\n", strings.Join(miss, ", "))
	}
	w("## SoC\n\n- Model: %s\n", factStr(&p.SoC.Fact))
	if p.SoC.Family != nil {
		w("- Family: %s\n", factStr(p.SoC.Family))
	}
	if p.SoC.Revision != nil {
		w("- Revision (raw): %s\n", factStr(p.SoC.Revision))
	}
	if p.SoC.ChipID != nil {
		w("- Chip ID (raw): %s\n", factStr(p.SoC.ChipID))
	}
	w("\n## Board\n\n")
	for _, k := range []string{"model", "compatible", "vendor", "board_name", "hardware_revision"} {
		w("- %s: %s\n", k, factStr(p.Device[k]))
	}
	w("\n## RAM\n\n- Size (MiB): %s\n", factStr(p.Device["ram_mib"]))
	if mem, ok := p.DT["memory"].([]string); ok && len(mem) > 0 {
		w("- DT memory: %s\n", strings.Join(mem, ", "))
	}
	if banks, ok := p.UBoot["dram_banks"].([]string); ok {
		w("- U-Boot DRAM banks: %s\n", strings.Join(banks, ", "))
	}
	w("\n## UART\n\n")
	w("- Port settings: %v baud, 8N1, no flow control\n", p.UART["baud"])
	if m, ok := p.UART["markers"].(map[string]any); ok && len(m) > 0 {
		w("- Markers seen: %s\n", strings.Join(sortedKeys(m), ", "))
	}
	if br := p.BootROM; br["detected"] == true {
		w("- BootROM: entry `%v`, XMODEM receiver char `%v`\n", br["entry_sequence"], br["receiver_char"])
	}
	w("\n## Flash\n\n")
	w("| field | value |\n|---|---|\n")
	for _, x := range []struct {
		k string
		f *Fact
	}{{"type", p.Flash.Type}, {"manufacturer", p.Flash.Manufacturer}, {"device id", p.Flash.DeviceID}, {"total size", p.Flash.TotalSize},
		{"page size", p.Flash.PageSize}, {"erase block", p.Flash.EraseSize}, {"OOB", p.Flash.OOBSize}, {"ECC", p.Flash.ECC}, {"sub-page", p.Flash.SubPage}} {
		w("| %s | %s |\n", x.k, factStr(x.f))
	}
	w("\n### Partitions\n\n| # | name | offset | size | sources | confidence | contents |\n|---|---|---|---|---|---|---|\n")
	for _, e := range p.MTD {
		idx := ""
		if e.Index != nil {
			idx = fmt.Sprint(*e.Index)
		}
		var cs []string
		for _, c := range e.Contents {
			cs = append(cs, c.Kind+":"+c.Signature.Format)
		}
		conf := e.Confidence
		if e.Conflict {
			conf = "**CONFLICT**"
		}
		ds := ""
		if e.DeviceSpecific {
			ds = " (device-specific)"
		}
		w("| %s | %s%s | %s | %s | %s | %s | %s |\n", idx, e.Name, ds, hx(e.Offset), hx(e.Size), strings.Join(e.Source, ", "), conf, strings.Join(cs, " "))
	}
	if p.UBI.Detected {
		w("\n### UBI\n\n- MTD: %s\n- PEB: %s\n- LEB: %s\n- VID header offset: %s\n- data offset: %s\n\n", factStr(p.UBI.MTD), factStr(p.UBI.PEBSize), factStr(p.UBI.LEBSize), factStr(p.UBI.VIDHdrOffset), factStr(p.UBI.DataOffset))
		for _, v := range p.UBI.Volumes {
			var cs []string
			for _, c := range v.Contents {
				cs = append(cs, c.Signature.Format)
			}
			w("- volume `%s` id %s type %s size %s %s\n", v.Name, fmtFactVal(v.ID.Value), fmtFactVal(v.Type.Value), fmtFactVal(v.SizeBytes.Value), strings.Join(cs, " "))
		}
	}
	w("\n## Device tree\n\n")
	if p.DT["available"] == true {
		w("- Sources: %v (primary %v)\n- Model: %v\n- Compatible: %v\n- Files: `dt/fdt.dtb`, `dt/fdt.dts`\n", p.DT["sources"], p.DT["primary"], p.DT["model"], p.DT["compatible"])
		if c, ok := p.DT["node_counts"].(map[string]int); ok {
			var parts []string
			for _, k := range sortedKeys(c) {
				parts = append(parts, fmt.Sprintf("%s=%d", k, c[k]))
			}
			w("- Node classes: %s\n", strings.Join(parts, ", "))
		}
	} else {
		w("- No DTB collected.\n")
	}
	w("\n## Ethernet / switch / PHY\n\n")
	writeJSONBlock(&b, p.Network, []string{"ethernet_controllers", "switch", "ports", "phys", "pcs", "interface_modes", "wan_lan_from_dt_labels", "uboot_mii_phys", "linux_interfaces", "openwrt_board_json_network"})
	w("\n## GPIO (buttons, LEDs)\n\n")
	writeJSONBlock(&b, p.GPIO, []string{"buttons", "leds", "linux_debug_gpio"})
	w("\n## Boot chain\n\n| stage | detected | version | location | format | hash |\n|---|---|---|---|---|---|\n")
	for _, st := range p.BootChain {
		det := "?"
		if st.Detected != nil {
			det = "yes"
		}
		h := ""
		if st.Hash != nil {
			if v, ok := st.Hash["sha256"].(string); ok && len(v) > 16 {
				h = v[:16] + "…"
			} else if v, ok := st.Hash["crc32"].(string); ok {
				h = "crc32 " + v
			}
		}
		w("| %s | %s | %s | %s | %s | %s |\n", st.Stage, det, st.Version, st.Location, st.Format, h)
		if st.FIP != nil {
			for _, e := range st.FIP.Entries {
				w("|  ↳ FIP | | %s | +0x%x | %d bytes | %s |\n", e.Name, e.Offset, e.Size, e.UUID)
			}
		}
	}
	w("\n## U-Boot capabilities\n\n")
	if p.UBoot["detected"] == true {
		w("- Version: %v (%v)\n- Prompt: `%v`\n", p.UBoot["version"], p.UBoot["source"], p.UBoot["prompt"])
		if c, ok := p.Capabilities["commands"].(map[string]bool); ok {
			var yes, no []string
			for _, k := range sortedKeys(c) {
				if c[k] {
					yes = append(yes, k)
				} else {
					no = append(no, k)
				}
			}
			w("- Present: %s\n- Absent: %s\n", strings.Join(yes, ", "), strings.Join(no, ", "))
		}
	} else {
		w("- U-Boot not reached.\n")
	}
	w("\n## Device-specific data (do not clone)\n\n")
	for _, id := range p.Identity {
		w("- %s%s: %s\n", id.Partition, id.Location, strings.Join(id.Evidence, "; "))
	}
	w("\n## Conflicts\n\n")
	if len(p.Conflicts) == 0 {
		w("None.\n")
	}
	for _, c := range p.Conflicts {
		w("- `%s`: %s\n", c.Field, conflictText(c))
	}
	w("\n## Warnings\n\n")
	for _, x := range p.Warnings {
		w("- %s\n", x)
	}
	w("\n---\nPatch generation for U-Boot is out of scope for this version; use this report together with `dt/fdt.dts` and the raw files in the bundle.\n")
	return b.String()
}

func writeJSONBlock(b *strings.Builder, m map[string]any, keys []string) {
	sub := map[string]any{}
	for _, k := range keys {
		if v, ok := m[k]; ok && v != nil {
			sub[k] = v
		}
	}
	if len(sub) == 0 {
		b.WriteString("No data.\n")
		return
	}
	j, _ := json.MarshalIndent(sub, "", "  ")
	b.WriteString("```json\n" + string(j) + "\n```\n")
}

func ursusFlasherDraft(p *Profile) map[string]any {
	var parts []map[string]any
	var safeRanges []map[string]any
	var devSpecific []string
	for _, e := range p.MTD {
		pm := map[string]any{"name": e.Name, "offset": e.Offset, "size": e.Size, "confidence": e.Confidence, "conflict": e.Conflict, "device_specific": e.DeviceSpecific}
		var fm []string
		for _, c := range e.Contents {
			if c.Kind == "head" {
				fm = append(fm, c.Signature.Format)
			}
		}
		pm["head_format"] = fm
		parts = append(parts, pm)
		if e.Offset != nil && e.Size != nil && !e.Conflict {
			safeRanges = append(safeRanges, map[string]any{"name": e.Name, "offset": *e.Offset, "size": *e.Size, "mode": "read-only backup"})
		}
		if e.DeviceSpecific {
			devSpecific = append(devSpecific, e.Name)
		}
	}
	var transports []string
	if p.BootROM["xmodem"] == true || p.BootROM["press_x"] == true {
		transports = append(transports, "bootrom-uart-xmodem")
	}
	if d, ok := p.Capabilities["derived"].(map[string]bool); ok {
		if d["uart_xmodem_load"] {
			transports = append(transports, "uboot-uart-loadx/loady")
		}
		if d["tftp_recovery"] {
			transports = append(transports, "uboot-tftp")
		}
		if d["http_recovery"] {
			transports = append(transports, "uboot-httpd")
		}
	}
	if p.Linux["detected"] == true {
		transports = append(transports, "linux-shell")
	}
	bl := "unknown"
	if v, ok := p.UBoot["version"].(string); ok {
		bl = v
	} else {
		for _, st := range p.BootChain {
			if st.Stage == "bl33/u-boot" && st.Version != "" {
				bl = st.Version
			}
		}
	}
	return map[string]any{
		"schema":         "ursusflasher-device-draft-v0",
		"status":         "DRAFT — generated by the probe; never use as a production profile without review",
		"source_profile": map[string]any{"schema": p.Schema, "created": p.Created, "generator": p.Generator},
		"model_detection": map[string]any{
			"dt_compatible": p.Device["compatible"],
			"dt_model":      p.Device["model"],
			"board_name":    p.Device["board_name"],
		},
		"soc":                p.SoC.Fact,
		"flash":              map[string]any{"type": p.Flash.Type, "total_size": p.Flash.TotalSize, "page_size": p.Flash.PageSize, "erase_block_size": p.Flash.EraseSize, "oob_size": p.Flash.OOBSize},
		"partition_map":      parts,
		"bootloader_type":    bl,
		"recovery_transport": transports,
		"safe_backup_ranges": safeRanges,
		"device_specific":    devSpecific,
		"ubi_layout":         p.UBI,
		"conflicts":          p.Conflicts,
		"missing":            p.Completeness["missing"],
		"production_ready":   false,
	}
}
